# Copyright (C) 2020 Google Inc.
#
# This file has been licensed under Apache 2.0 license.  Please see the LICENSE
# file at the root of the repository.

FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
    asymptote \
    bash \
    calibre \
    drawtiming \
    gladtex \
    graphviz \
    pandoc \
    plantuml \
    python3 \
    scons \
    texlive-fonts-recommended \
    librsvg2-bin \
    texlive-latex-extra \
    libgmp-dev
