name: Release
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 6.0.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Build book"
        run: "cd ebook-example && bazel build //:html_chunked && ls -lR"
      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: filmil/hdlfactory.com.template
          publish_dir: ./bazel-bin/html_chunked.d/html_chunked
          destination_dir: static/html_chunked
          publish_branch: main
          deploy_key: "${{ secrets.DEPLOY_KEY }}"
