name: Release
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 6.0.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Build ebook-example"
        run: "cd ebook-example && bazel build //:html_chunked"
      - name: "Build bazel-ebook manual"
        run: "bazel build //:bazel_ebook_html"
      - name: "Examine the environment"
        run: "ls -lR && ls -lR ./ebook-example/bazel-bin && ls -lR ./ebook-example/bazel-bin/html_chunked.d"
      - name: "Deploy ebook-example"
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: filmil/hdlfactory.com.template
          publish_dir: ./ebook-example/bazel-bin/html_chunked.d/html_chunked
          destination_dir: static/html_chunked
          publish_branch: main
          deploy_key: "${{ secrets.DEPLOY_KEY }}"
      - name: "Deploy bazel_ebook_html"
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: filmil/hdlfactory.com.template
          publish_dir: ./bazel-bin/bazel_ebook_html.d/bazel_ebook_html
          destination_dir: static/html_chunked
          publish_branch: main
          deploy_key: "${{ secrets.DEPLOY_KEY }}"
